### ISSUE TITLE
Error for inactive websites

### ISSUE THREAD

**Issue by justoverclockl** [datlechin/flarum-link-preview#2]
![Immagine 2022-04-27 122214](https://user-images.githubusercontent.com/79002016/165497897-08a9cbb1-9f69-4ad7-b1d2-26a790b78d41.png)

If someone post a website that does not exist, flarum run an "oops something went wrong" alert....

**Comment by datlechin** [comment]
What is website you entered?
I try some website does not exist but Flarum not show **Oops...**

https://vieit.net/d/46-lorem-ipsum/3

**Comment by justoverclockl** [comment]
https://justoverclock.it/

**Comment by datlechin** [comment]
oops, maybe it's because of SSL, I'll check
