### ISSUE TITLE
Unrelated to Flarum

### ISSUE THREAD

**Issue by efast1568** [datlechin/flarum-link-preview#25]
To  port this extensions to a Laravel-based platform like [@waterhole](https://github.com/waterholeforum), is it a challenging task?
https://waterhole.subarist.net/  
^_^

**Comment by datlechin** [comment]
I think it’s possible.

**Comment by efast1568** [comment]
Do you have any interest in porting flarum-link-preview to Waterhole? I might be able to pay a bit of a fee; I like this extension so much, even though my site doesn't have many visitors.

**Comment by datlechin** [comment]
Hi @efast1568, please feel free to email me at datlechin@gmail.com or DM me on Telegram [@datngoquoc](https://t.me/datngoquoc)
