### ISSUE TITLE
Link preview is changing my links

### ISSUE THREAD

**Issue by orschiro** [datlechin/flarum-link-preview#4]
Hi!

Thanks for your great extension.

However, it's changing my link https://app.sheetgo.com/account/usage into https://app.sheetgo.com.

Video: [Screen recording (4).webm](https://user-images.githubusercontent.com/170947/189646064-e96ef5dc-54ac-49ec-bcf3-ab15d2b64b0c.webm)

**Comment by datlechin** [comment]
thanks for the report.

**Comment by orschiro** [comment]
You're welcome!

**Comment by datlechin** [comment]
so weird, it didn't change any links for me

![Screenshot 2022-09-13 at 15 35 13](https://user-images.githubusercontent.com/56961917/189853333-15bf7c09-74c7-4d3f-b409-7a57c2e04b41.png)

**Comment by orschiro** [comment]
Thanks for testing as well!

Any idea why it's not working for us then?

See this example: https://community.sheetgo.com/d/275-testing-link-preview

**Comment by spekulatius** [comment]
Hey @orschiro,

I've built [the scraping lib](https://github.com/spekulatius/PHPScraper) used by @datlechin's link-preview extension. I might have an idea: Does this page require to be signed in? If so, it might redirect and lead to the observed behavior.

Cheers,
Peter

**Comment by orschiro** [comment]
Hi Peter,

Yes, it indeed does require people to be signed in.

How can we go about this issue?

**Comment by spekulatius** [comment]
Hey @orschiro,

the scaper can really only access what is "available to access" for it. Any other scraper would have the same problem.

But there are options to get it working: for example, you could use a simple "mock page" with containing only the required data and return this page based on the agent. By default it contains phpscraper as an identifier in the user agent string. This would be transparent for users. Do you think this could work?

Cheers,
Peter

**Comment by orschiro** [comment]
I'm all good with that. Final word is with @datlechin :)

**Comment by datlechin** [comment]
> Hey @orschiro,
> 
> the scaper can really only access what is "available to access" for it. Any other scraper would have the same problem.
> 
> But there are options to get it working: for example, you could use a simple "mock page" with containing only the required data and return this page based on the agent. By default it contains phpscraper as an identifier in the user agent string. This would be transparent for users. Do you think this could work?
> 
> Cheers, Peter

May it works if I use `userAgent` based on client?
```php
->setAgent($_SERVER['HTTP_USER_AGENT'])
```

**Comment by spekulatius** [comment]
The agent only helps if the accessed site changes the response from a redirect to a mock page as described. Can you create a simple page returning only the OG data, if the agent contains "phpscraper" @orschiro?

**Comment by orschiro** [comment]
Maybe the simplest solution would be always displaying the original link
below the preview block so people have an alternative in case the preview
breaks?

**Comment by datlechin** [comment]
@orschiro I haven't thought of this yet, hope this release works for you
https://github.com/datlechin/flarum-link-preview/releases/tag/v1.0.1

**Comment by orschiro** [comment]
Wonderful, thanks! :)

**Comment by orschiro** [comment]
Sorry but I'm not sure what you mean by simple page that only contains OG
data.

**Comment by spekulatius** [comment]
> Sorry but I'm not sure what you mean by simple page that only contains OG data.

I was thinking of exposing the desired values for the page that is usually behind the login. Here it would be `og:site_name`, `og:title`, `og:description`, `og:image` of https://app.sheetgo.com/account/usage. The redirect needs to be tweaked too to make it work. Did the earlier solution by @datlechin work for you?
